
export const ORDERDATA_GET_REQUEST = "ORDERDATA_GET_REQUEST";
export const ORDERDATA_GET_SUCCESS = "ORDERDATA_GET_SUCCESS";
export const ORDERDATA_GET_FAILURE = "ORDERDATA_GET_FAILURE";
export const ORDERDATA_UPDATE_REQUEST = "ORDERDATA_UPDATE_REQUEST";
export const ORDERDATA_ADD_SUCCESS = "ORDERDATA_ADD_SUCCESS";