
export const TASK_GET_REQUEST = "TASK_GET_REQUEST";
export const TASK_GET_SUCCESS = "TASK_GET_SUCCESS";
export const TASK_GET_FAILURE = "TASK_GET_FAILURE";
export const TASK_ADDED_SUCCESS="TASK_ADDED_SUCCESS";
export const TASK_UPDATE_SUCCESS="TASK_UPDATE_SUCCESS";
export const TASK_DELETE_SUCCESS="TASK_DELETE_SUCCESS";