export const SET_PRODUCT_CATEGORY = "SET_PRODUCT_CATEGORY";
export const SET_PRODUCT_MENU_CLICKED = "SET_PRODUCT_MENU_CLICKED";
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART = "REMOVE_ITEM_FROM_CART";
export const SET_LOGS = "SET_LOGS";
